### ISSUE TITLE
May I ask you to show me UnixStream example?

### ISSUE THREAD

**Issue by ghmlee** [sfackler/rust-unix-socket#1]
Recently I found std::old_io::net::pipe::UnixStream will be deprecated and also some people mentioned your unix_socket. If you are not busy (of course you are busy), may I ask you to show me UnixStream example? Thanks. :)

**Comment by sfackler** [comment]
Sure - it's pretty straightforward. You open a `UnixStream` with the `connect` method which is passed the path to the unix socket file on the filesystem:

``` rust
let mut socket = try!(UnixStream::connect("/run/postgres/.s.PGSQL.5432");
```

`UnixStream` implements `Read` and `Write`, so you can use it like any other stream:

``` rust
let mut buf = vec![];
try!(socket.read_to_end(&mut buf));
```

**Comment by ghmlee** [comment]
@sfackler Thank you so much. :)
