### ISSUE TITLE
Feature request: Add FromRawFd impls

### ISSUE THREAD

**Issue by mohtar** [sfackler/rust-unix-socket#10]
Add `FromRawFd` trait implementations for `UnixListener` and `UnixStream`. The structs in the standard library `TcpListener` and `TcpStream` have it, and the `Unix*` structs in mio have it as well.

**Comment by sfackler** [comment]
I've added implementations and published them in v0.4.1. They're behind the `from_raw_fd` feature gate since the trait isn't stable in Rust 1.0.0.
