### ISSUE TITLE
Have a way to split a `UnixStream` into reading and writing halves.

### ISSUE THREAD

**Issue by canndrew** [sfackler/rust-unix-socket#7]
I have a `UnixStream` that I want to read from in one thread and write to in another thread. It would be cool if `UnixStream` had a function to split it into two sides:

```
fn split(self) -> (UnixReader, UnixWriter);
```

**Comment by sfackler** [comment]
The `try_clone` method will allow you to get a second `UnixSocket` that uses the same connection as the main one just like `TcpStream`, `UdpStream`, `File`, etc in the standard library: http://sfackler.github.io/rust-unix-socket/doc/unix_socket/struct.UnixStream.html#method.try_clone
